/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontPkg = null;

  static const IconData database = IconData(0xf305, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData markdown = IconData(0xf306, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe = IconData(0xf309, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData light_bulb = IconData(0xf30a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData desktop_download = IconData(0xf348, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
